<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Market\Doctrine;
use MSBios\Market\Resource\Doctrine\Entity\Product;
?>
<h2><?= $this->brand->getName(); ?></h2>
<ul class="list-inline">
    <li class="list-inline-item">
        Сортировать по
    </li>
    <li class="list-inline-item">
        <a href="">умолчанию</a>
    </li>
    <li class="list-inline-item">
        <a href="">цене</a>
    </li>
    <li class="list-inline-item">
        <a href="">названию</a>
    </li>
</ul>

<?php /** @var Product $product */ ?>
<?php foreach ($this->products as $product): ?>
    <?= $this->partial('partial/product', ['product' => $product]); ?>
<?php endforeach; ?>
