<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Market\Doctrine;

?>
<h2><?= $this->product->getName(); ?></h2>

<div class="row">
    <div class="col-md-4">
        <img src="https://via.placeholder.com/500" class="img-responsive" alt="Responsive image">
    </div>
    <div class="col-md-8">
        <?= $this->product->getContent(); ?>
    </div>
</div>