<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Market\Doctrine;

use MSBios\Market\Resource\Doctrine\Entity\Product;
use MSBios\Market\Resource\Doctrine\Entity\Variant;
use Zend\Form\Element;

/** @var Product $product */
$product = $this->product;
?>
<div class="row" style="margin-bottom: 30px;">
    <div class="col-md-3">
        <img src="https://via.placeholder.com/300" class="img-responsive" alt="Responsive image"/>
    </div>
    <div class="col-md-9">
        <a href="<?= $this->url('home/products/view', ['id' => $product->getId(), 'slug' => $product->getSlug()]); ?>"
           class="h3">
            <?= $product->getName(); ?>
        </a>
        <?= $product->getAnnotation(); ?>

        <?php
        /** @var array $variants */
        $variants = $product->getVariants();
        ?>
        <?php if (count($variants)) : ?>
            <form action="<?= $this->url('home/cart'); ?>" method="post">

                <ul>

                    <?php if (count($variants) > 1) : ?>

                        <?php /** @var Variant $variant */ ?>
                        <?php foreach ($variants as $variant): ?>
                            <li>
                                <?= $this->formElement((new Element\Radio('variantid'))->setValueOptions([
                                    $variant->getId() => $variant->getName()
                                        . ' ' . $variant->getPrice()
                                ])); ?>
                            </li>
                        <?php endforeach; ?>

                    <?php else: ?>
                        <?php /** @var Variant $variant */ ?>
                        <?php foreach ($variants as $variant): ?>
                            <li>
                                <?= $variant->getPrice(); ?>
                                <?= $this->formElement((new Element\Hidden('variantid'))->setAttributes([
                                    'value' => $variant->getId()
                                ])); ?>
                            </li>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </ul>
                <?= $this->formElement((new Element\Hidden('productid'))->setAttributes([
                    'value' => $product->getId()
                ])); ?>
                <a href="#" class="btn btn-default">В корзину</a>
            </form>
        <?php endif; ?>
    </div>
</div>