<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Market\Doctrine;

use MSBios\Market\Resource\Doctrine\Entity\Product;

/** @var Product $product */
$product = $this->product;

?>
<div class="row" style="margin-bottom: 30px;">
    <div class="col-md-3">
        <img src="https://via.placeholder.com/300" class="img-responsive" alt="Responsive image"/>
    </div>
    <div class="col-md-9">
        <a href="<?= $this->url('home/products/view', ['id' => $product->getId(), 'slug' => $product->getSlug()]); ?>"
           class="h3">
            <?= $product->getName(); ?>
        </a>
        <?= $product->getAnnotation(); ?>

        <?= $this->partial('partial/variants', ['product' => $product]); ?>
    </div>
</div>