<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Market\Doctrine;

use MSBios\Market\Resource\Doctrine\Entity\Variant;
use Zend\Form\Element;

/** @var array $variants */
$variants = $this->product->getVariants();
?>

<?php if (count($variants)) : ?>
    <form action="<?= $this->url('home/cart'); ?>" method="post">
        <ul>
            <?php if (count($variants) > 1) : ?>

                <?php /** @var Variant $variant */ ?>
                <?php foreach ($variants as $variant): ?>
                    <li>
                        <?= $this->formRadio((new Element\Radio('variantid', [
                            'value_options' => [
                                $variant->getId() => ''
                            ]
                        ]))); ?>
                        <?= $variant->getName(); ?>
                        <?php if ($variant->hasCompare()) : ?>
                            <span class="text-muted">
                                <del><?= $variant->getCompare(); ?></del>
                            </span>
                        <?php endif; ?>
                        <?= $variant->getPrice(); ?>
                    </li>
                <?php endforeach; ?>

            <?php else: ?>
                <?php /** @var Variant $variant */ ?>
                <?php foreach ($variants as $variant): ?>
                    <li>
                        <?= $variant->getPrice(); ?>
                        <?= $this->formElement((new Element\Hidden('variantid'))->setAttributes([
                            'value' => $variant->getId()
                        ])); ?>
                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
        </ul>
        <?= $this->formElement((new Element\Hidden('productid'))->setAttributes([
            'value' => $this->product->getId()
        ])); ?>
        <button type="submit" class="btn btn-default">В корзину</button>
    </form>
<?php endif; ?>

