<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Market\Doctrine;
?>

<?php /** @var \Zend\View\Helper\FlashMessenger $flash */ ?>
<?php $flash = $this->flashMessenger(); ?>

<?php if ($flash->hasSuccessMessages()) : ?>

    <div class="alert alert-success no-border">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
            <span class="sr-only">Close</span>
        </button>
        <span class="text-semibold"><?= $this->translate('Success!'); ?></span>
        <?= implode(', ', $flash->getSuccessMessages()); ?>
    </div>

<?php endif; ?>

<?php if ($flash->hasInfoMessages()) : ?>

    <div class="alert alert-info no-border">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
            <span class="sr-only">Close</span>
        </button>
        <span class="text-semibold"><?= $this->translate('Info!'); ?></span>
        <?= implode(', ', $flash->getInfoMessages()); ?>
    </div>

<?php endif; ?>

<?php if ($flash->hasWarningMessages()) : ?>

    <div class="alert alert-danger no-border">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
            <span class="sr-only">Close</span>
        </button>
        <span class="text-semibold"><?= $this->translate('Warning!'); ?></span>
        <?= implode(', ', $flash->getWarningMessages()); ?>
    </div>

<?php endif; ?>

<h2>Корзина</h2>

<table class="table table-condensed table-striped">
    <tr>
        <th>Photo</th>
        <th>Name</th>
        <th>Variant</th>
        <th>Price</th>
        <th>Amount</th>
    </tr>
<?php foreach ($this->order->getPurchases() as $purchase): ?>
    <?php $variant = $purchase->getVariant(); ?>
    <tr>
        <td></td>
        <td><?= $variant->getProduct()->getName(); ?></td>
        <td><?= $variant->getName(); ?></td>
        <td><?= $variant->getPrice(); ?></td>
        <td><?= $purchase->getAmount(); ?></td>
    </tr>
<?php endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <th><?= $this->order->getPrice(); ?></th>
        <th><?= $this->order->getAmount(); ?></th>
    </tr>
</table>
