<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Market\Doctrine;

use MSBios\Market\Resource\Doctrine\Entity\Brand;

?>

<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('default/css/style.css'))
        ->prependStylesheet($this->basePath('default/css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('default/css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('default/js/bootstrap.min.js'))
        ->prependFile($this->basePath('default/js/jquery-3.1.0.min.js'))
    ?>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img src="<?= $this->basePath('default/img/zf-logo-mark.svg') ?>" height="28"
                     alt="Zend Framework <?= \MSBios\Application\Module::VERSION ?>"/>&nbsp;MSBios Market Doctrine
            </a>
        </div>

        <div class="collapse navbar-collapse">
            <?php $this->navigation('Zend\Navigation\Default')
                ->menu()
                ->setUlClass('nav navbar-nav')
                ->setPartial('partial/menu.phtml')
                ->setMaxDepth(0)
                ->render(); ?>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="<?= $this->url('home/cart'); ?>">Корзина</a></li>
            </ul>

        </div>
    </div>
</nav>
<div class="container">

    <h1>MSBios Market Doctrine Module</h1>

    <div class="row">
        <div class="col-md-3">

            <form role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search" name="name">
                </div>
            </form>

            <?= $this->partial('partial/categories.phtml', ['categories' => $this->categories]); ?>
            <h3>Все бренды:</h3>
            <?php /** @var Brand $brand */ ?>
            <?php foreach ($this->brands as $brand): ?>
                <a href="<?= $this->url('home/brands', ['id' => $brand->getId(), 'slug' => $brand->getSlug()]); ?>">
                    <?= $brand->getName();?>
                </a>
            <?php endforeach; ?>
        </div>
        <div class="col-md-9">
            <?= $this->content ?>
        </div>
    </div>

    <hr>

    <footer>
        <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved. MSBios
            version <?= \MSBios\Module::VERSION; ?></p>
    </footer>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
